### ISSUE TITLE
Preload responsive images

### ISSUE THREAD

**Issue by mrodz** [devinlizardi/canan-tolon-rebuild#6]
Hello! GitHub sent me a notification about this project and I checked it out. One tiny possible enhancement I noticed is image preloading for the links on the landing page.

After hovering over a link, the pretty background image will load and replace the text—super neat. However, the first time you do this, the browser hasn't cached the image yet and renders it for the first time, which can lag a bit depending on a person's computer for high-res images.

Consider adding...
```
<link rel="preload" as="image" href="path/to/important.png">
``` 
... in the <head> of the static html for each image to tell the browser to pre-cache it. That way, they're ready when the user hovers over the links!

Awesome site man :)

**Comment by devinlizardi** [comment]
Mateo! Thanks for commenting man, this is a great suggestion.

This is definitely an important issue with the site as-is, right now the (massive) png files are being bundled on the production server and the browser has to sent a fetch request _every_ time the user hovers over one of the links. I'm currently waiting for the artists approval on the design, but this is exactly the kind of patch that'll take a second to do and make things faster. 

Do you have much experience with React? I have a potential client interested in building a different application if you're interested, right now I'm too busy for it.

**Comment by mrodz** [comment]
I'd say I'm relatively familiar--I've made both websites and web apps with it before. I'd jump at the chance to get work experience in + better my skills with the framework, and I really appreciate you looking out for me like that.

My email is [mateotrodriguez@gmail.com](mailto:mateotrodriguez@gmail.com). Let's carry this conversation there!
